import streamlit as st
from ui_utils import *

hide_sidebar(set_wide=False)

st.title("Welcome to the AI Learning Study")

st.markdown(
"**You are invited to take part in a research study about how people learn and explain scientific concepts while interacting with an AI system and receiving feedback from it.**  \n\n"
"Before beginning, please review and complete the consent form here:  \n"
"[Open the Study Consent Form](https://docs.google.com/forms/d/e/1FAIpQLSdKKNAJYxTeLA9tOZKncFi4ZkGwseZEKHX5XJ10ymr3rH5Ofg/viewform?usp=dialog)"
)
st.divider()
intro = """
In this study, you will (**please read carefully**):

• Watch a short video explaining a scientific concept  
• Write a brief summary of your understanding of the concept just learned  
• Receive feedback generated by an AI system with the opportunity to chat with the AI  
• Revise your explanation based on that feedback  
• Answer transfer test questions  
• Asnwer post-study questions  

The entire study takes approximately 15–20 minutes to complete.
"""

st.write(intro)

html_reminder = """
<div style='background-color: #ff6347; color: #f0f2f6; padding: 10px;'>
    Please DO NOT refresh the web page throughout the studyl; otherwise, your participation may be invalid.
</div>
"""
st.markdown(html_reminder, unsafe_allow_html=True)

if st.button("Next"):
    st.switch_page("pages/pre_study.py")